In [2]:
'''
EXERCICIOS NUMPY
'''
import numpy as np

In [3]:
'''
Exercício 1
Inspecionando um Array NumPy

Um objeto numpy possui atributos e métodos, herdados da classe (numpy.ndarray). Crie um array  e inspecione os seguintes atributos:

shape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;
size: número total de elementos do array;
ndim: número de dimensões (eixos);
nbytes: número de bytes utilizado no armazenamento dos dados;
dtype: data type dos elementos do array.
'''

'\nExercício 1\nInspecionando um Array NumPy\n\nUm objeto numpy possui atributos e métodos, herdados da classe (numpy.ndarray). Crie um array  e inspecione os seguintes atributos:\n\nshape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;\nsize: número total de elementos do array;\nndim: número de dimensões (eixos);\nnbytes: número de bytes utilizado no armazenamento dos dados;\ndtype: data type dos elementos do array.\n'

In [4]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('Shape :', array.shape)
print('Size: ', array.size)
print('Ndim: ', array.ndim)
print('Nbytes: ', array.nbytes)
print('Dtype: ', array.dtype)

Shape : (10,)
Size:  10
Ndim:  1
Nbytes:  80
Dtype:  int64


In [5]:
'''
Exercício 2
Com base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. 
Verifique se o argumento inserido é de fato um objeto numpy.
 Use também a função built-in type() para verificar a classe do objeto.
'''

'\nExercício 2\nCom base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. \nVerifique se o argumento inserido é de fato um objeto numpy.\n Use também a função built-in type() para verificar a classe do objeto.\n'

In [6]:
def inspecionar_array(array):
  if isinstance(array, np.ndarray):
    print('Shape :', array.shape)
    print('Size: ', array.size)
    print('Ndim: ', array.ndim)
    print('Nbytes: ', array.nbytes)
    print('Dtype: ', array.dtype)
    print('Type: ', type(array))
    return array  
  else:
    return 'O objeto inserido não e um NumPy'
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
inspecionar_array(array)
inspecionar_array(list)




Shape : (10,)
Size:  10
Ndim:  1
Nbytes:  80
Dtype:  int64
Type:  <class 'numpy.ndarray'>


'O objeto inserido não e um NumPy'

In [7]:
'''
Exercício 3
Use a função np.array() para criar os arrays unidimensionais listados abaixo:

a) Use uma lista como argumento e obtenha:

array([-1,  4,  7,  9])


b) Use a função range() e obtenha:

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


c)Use uma tupla como argumento e obtenha:

array([10, 11, 12, 13, 14])


d) Use a função range() e obtenha:
   
array([1990, 1995, 2000, 2005, 2010, 2015, 2020])


e) Use a função range() e obtenha:

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

f) Obtenha:
array(100)
'''

'\nExercício 3\nUse a função np.array() para criar os arrays unidimensionais listados abaixo:\n\na) Use uma lista como argumento e obtenha:\n\narray([-1,  4,  7,  9])\n\n\nb) Use a função range() e obtenha:\n\narray([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])\n\n\nc)Use uma tupla como argumento e obtenha:\n\narray([10, 11, 12, 13, 14])\n\n\nd) Use a função range() e obtenha:\n   \narray([1990, 1995, 2000, 2005, 2010, 2015, 2020])\n\n\ne) Use a função range() e obtenha:\n\narray([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,\n       1910, 1900])\n\nf) Obtenha:\narray(100)\n'

In [8]:
A = np.array([-1, 4, 7, 9])
A

array([-1,  4,  7,  9])

In [9]:
B = np.array(range(1, 11))
B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
C = (10, 11, 12, 13, 14)
np.array(C)

array([10, 11, 12, 13, 14])

In [11]:
C = np.array(range(1990, 2025, 5))
C

array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

In [12]:
D = np.array(range(2020, 1890, -10))
D

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

In [13]:
array = np.array(100)
array

array(100)

In [14]:
'''
A função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. 
Podemos especificar como argumentos o shape e o tipo de dado dtype do array. 
Use esta função para criar os arrays a seguir:

a) array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


b)array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
       

c)array([[1, 1],
       [1, 1],
       [1, 1]])
'''

'\nA função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. \nPodemos especificar como argumentos o shape e o tipo de dado dtype do array. \nUse esta função para criar os arrays a seguir:\n\na) array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])\n\n\nb)array([[1., 1., 1., 1.],\n       [1., 1., 1., 1.],\n       [1., 1., 1., 1.],\n       [1., 1., 1., 1.]])\n       \n\nc)array([[1, 1],\n       [1, 1],\n       [1, 1]])\n'

In [15]:
A = np.ones(10)
A

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
B = np.ones(shape = (4, 4))
B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
C = np.ones(shape = (3, 2))
C

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
'''
A função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. 
Podemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). 
Use esta função para criar os arrays a seguir:

a)array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


b)array([[0., 0.],
       [0., 0.]])  
       

c)array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

'''

'\nA função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. \nPodemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). \nUse esta função para criar os arrays a seguir:\n\na)array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])\n\n\nb)array([[0., 0.],\n       [0., 0.]])  \n       \n\nc)array([[0., 0., 0., 0., 0., 0.],\n       [0., 0., 0., 0., 0., 0.],\n       [0., 0., 0., 0., 0., 0.],\n       [0., 0., 0., 0., 0., 0.]])\n\n'

In [19]:
A = np.zeros(10)
A

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
B = np.zeros(shape=(2, 2))
B

array([[0., 0.],
       [0., 0.]])

In [21]:
C = np.zeros(shape=(4, 6))
C

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
'''
Crie os arrays a seguir:
a)array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])


b)array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])


c)array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])
       

Dica: use np.arange() ou np.array(range()).
'''

'\nCrie os arrays a seguir:\na)array([[10],\n       [15],\n       [20],\n       [25],\n       [30],\n       [35],\n       [40],\n       [45]])\n\n\nb)array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])\n\n\nc)array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],\n       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],\n       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],\n       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],\n       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])\n       \n\nDica: use np.arange() ou np.array(range()).\n'

In [23]:
A = np.array(range(10, 50, 5)).reshape(8, 1)
A

array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])

In [24]:
B = np.array(range(-50, 0, 5))
B

array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

In [25]:
C = np.array(range(50, 150, 2)).reshape(5, 10)
C

array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])

In [26]:
'''
Exercício 7
Utilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. 
Esta função permite criar um array com um shape e dtype definidos pelo usuário, 
preenchido com um determinado valor.

a)array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


b)array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])


c)array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

d)array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])


Dica: outra possibilidade seria obter os arrays com uma operação diferente, a partir da multiplicação de uma matriz preenchida com número 1 por um determinado valor.
'''

'\nExercício 7\nUtilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. \nEsta função permite criar um array com um shape e dtype definidos pelo usuário, \npreenchido com um determinado valor.\n\na)array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])\n\n\nb)array([[-5., -5., -5., -5.],\n       [-5., -5., -5., -5.],\n       [-5., -5., -5., -5.],\n       [-5., -5., -5., -5.]])\n\n\nc)array([[3, 3, 3],\n       [3, 3, 3],\n       [3, 3, 3]])\n\nd)array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],\n       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])\n\n\nDica: outra possibilidade s

In [27]:
A = np.full(shape=(1,10), fill_value=5 , dtype=float)
A

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [28]:
B = np.full(shape=(4, 4), fill_value = -5, dtype=float)
B

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [29]:
C = np.full(shape=(3, 3), fill_value = 3, dtype=int)
C

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [30]:
D = np.full(shape=(10, 10), fill_value = 50, dtype=int)
D

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [31]:
'''
Defina o array K e verifique se há dados ausentes (missing data). Use a função np.isnan().
array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [100.,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])
'''

'\nDefina o array K e verifique se há dados ausentes (missing data). Use a função np.isnan().\narray([[ nan,   1.,  10.,   0.],\n       [ nan,  nan,  nan,  nan],\n       [100.,  50.,  nan, -25.],\n       [ 30.,  nan,  nan, 130.]])\n'

In [32]:
K = np.array([
    [np.nan, 1, 10, 0],
    [np.nan,np.nan,np.nan,np.nan],
    [100, 50, np.nan, -25],
    [30, np.nan, np.nan, 130]])

In [33]:
print(np.isnan(K))

[[ True False False False]
 [ True  True  True  True]
 [False False  True False]
 [False  True  True False]]


In [34]:
print(f'Há {np.isnan(K).sum()} dados ausentes em K')

Há 8 dados ausentes em K


In [35]:
'''
Exercício 9
A função np.linspace() retorna um array com números contendo espaçamento uniforme em um intervalo definido. 
Crie um array com números dentro do intervalo [1,21] em 5 partes.

Retorno esperado:
array([ 1.,  6., 11., 16., 21.])
'''

'\nExercício 9\nA função np.linspace() retorna um array com números contendo espaçamento uniforme em um intervalo definido. \nCrie um array com números dentro do intervalo [1,21] em 5 partes.\n\nRetorno esperado:\narray([ 1.,  6., 11., 16., 21.])\n'

In [36]:
np.linspace(1, 21, 5)

array([ 1.,  6., 11., 16., 21.])

In [37]:
'''
Exercício 10
A função np.logspace() retorna números com espaçamento uniforme em uma escala logarítmica. 
Crie um array com números dentro do intervalo [1, 51] em 10 partes com a função np.logspace().

Retorno esperado:
array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])
'''

'\nExercício 10\nA função np.logspace() retorna números com espaçamento uniforme em uma escala logarítmica. \nCrie um array com números dentro do intervalo [1, 51] em 10 partes com a função np.logspace().\n\nRetorno esperado:\narray([[1.00000000e+01],\n       [3.59381366e+06],\n       [1.29154967e+12],\n       [4.64158883e+17],\n       [1.66810054e+23],\n       [5.99484250e+28],\n       [2.15443469e+34],\n       [7.74263683e+39],\n       [2.78255940e+45],\n       [1.00000000e+51]])\n'

In [38]:
np.logspace(1, 51, 10).reshape(10, 1)

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])

In [39]:
'''
Exercício 11
Use a função np.diag() para construir o array a seguir:
array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])
'''

'\nExercício 11\nUse a função np.diag() para construir o array a seguir:\narray([[ 5,  0,  0,  0,  0,  0],\n       [ 0, 10,  0,  0,  0,  0],\n       [ 0,  0, 15,  0,  0,  0],\n       [ 0,  0,  0, 20,  0,  0],\n       [ 0,  0,  0,  0, 25,  0],\n       [ 0,  0,  0,  0,  0, 30]])\n'

In [40]:
np.diag(range(5, 31, 5))

array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])

In [41]:
'''
Use a função np.eye() (ou ainda np.identity()) para obter o array seguir.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Dica: essa matriz é definida como matriz identidade, neste caso de ordem 10, e assume grande relevância em diversos cálculos computacionais, como veremos mais adiante.
'''

'\nUse a função np.eye() (ou ainda np.identity()) para obter o array seguir.\n\narray([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],\n       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],\n       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],\n       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],\n       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],\n       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],\n       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],\n       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],\n       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])\n\nDica: essa matriz é definida como matriz identidade, neste caso de ordem 10, e assume grande relevância em diversos cálculos computacionais, como veremos mais adiante.\n'

In [42]:
np.identity(10) #ou

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [44]:
'''
Exercício 14
Obtenha a soma dos elementos de cada array a seguir. Use a função np.sum(). 
Implemente uma solução com loop for, para tanto armazene os vetores em uma lista.
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

Retorno esperado:
Soma dos elementos do array 1:  55
Soma dos elementos do array 2:  255.0
Soma dos elementos do array 3:  1275
Soma dos elementos do array 4:  10056552148.564463
Soma dos elementos do array 5:  105
'''

'\nExercício 14\nObtenha a soma dos elementos de cada array a seguir. Use a função np.sum(). \nImplemente uma solução com loop for, para tanto armazene os vetores em uma lista.\nimport numpy as np\narray1 = np.arange(1,11)\narray2 = np.linspace(1,50,10)\narray3 = np.array(range(51))\narray4 = np.logspace(1,10,5)\narray5 = np.diag(range(5,31,5))\n\nRetorno esperado:\nSoma dos elementos do array 1:  55\nSoma dos elementos do array 2:  255.0\nSoma dos elementos do array 3:  1275\nSoma dos elementos do array 4:  10056552148.564463\nSoma dos elementos do array 5:  105\n'

In [45]:
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))
arrays = [array1, array2, array3, array4, array5]
for index, arrays in enumerate(arrays, start = 1):
  print(f'Soma dos elementos do array {index}: ', arrays.sum())

Soma dos elementos do array 1:  55
Soma dos elementos do array 2:  255.0
Soma dos elementos do array 3:  1275
Soma dos elementos do array 4:  10056552148.564463
Soma dos elementos do array 5:  105


In [46]:
'''
A partir da matriz definida abaixo obtenha: 
a) soma total dos elementos; 
b) soma das linhas ; 
c) soma das colunas.
import numpy as np
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)
'''

'\nA partir da matriz definida abaixo obtenha: \na) soma total dos elementos; \nb) soma das linhas ; \nc) soma das colunas.\nimport numpy as np\nmatriz = np.array(np.random.randint(1,100,15)).reshape(5,3)\n'

In [47]:
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)

In [48]:
A = matriz.sum()
A

839

In [49]:
B = matriz.sum(axis=1)
B

array([207, 164, 171, 126, 171])

In [50]:
C = matriz.sum(axis=0)
C

array([255, 232, 352])

In [51]:
'''
Exercício 16
Obtenha o valor máximo e o valor mínimo de cada array abaixo. Implemente uma solução com loop for.
import numpy as np
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))

Dica: para obter o valor máximo e mínimo de um array podemos usar array.max() e array.min() ( ou ainda max(array) e min(array)).
'''


'\nExercício 16\nObtenha o valor máximo e o valor mínimo de cada array abaixo. Implemente uma solução com loop for.\nimport numpy as np\narray1 = np.array([-1, 10, 3, 4, 7, 27])\narray2 = np.random.randint(-100,300,30)\narray3 = np.random.randn(10)\narray4 = np.array(range(50,10,-2))\n\nDica: para obter o valor máximo e mínimo de um array podemos usar array.max() e array.min() ( ou ainda max(array) e min(array)).\n'

In [52]:
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))
arrays = [array1, array2, array3, array4]

In [53]:
for index, array in enumerate(arrays, start = 1):
    print(f'Array {index}')
    print(f'Valor máximo: ', array.max())
    print(f'Valor mínimo: ', array.min())
    print()

Array 1
Valor máximo:  27
Valor mínimo:  -1

Array 2
Valor máximo:  299
Valor mínimo:  -92

Array 3
Valor máximo:  2.199959308149549
Valor mínimo:  -0.6395060728520217

Array 4
Valor máximo:  50
Valor mínimo:  12



In [54]:
'''
Exercício 17
Crie uma função que receba uma matriz como entrada e calcule:

    a) Valor máximo da matriz;

    b) Valor máximo por coluna;

    c) Valor máximo por linha;

    d) Valor mínimo da matriz;

    e) Valor mínimo por coluna;

    f) Valor mínimo por linha.



Exemplo de retorno para a matriz definida abaixo:
Input:

matriz = np.random.randint(-1000,1000,50).reshape(10,5)
info_matriz(matriz)
Output:

Valor máximo da matriz:  987
Valor máximo por coluna:  [959 987 597 748 719]
Valor máximo por linha:  [ 987  312  982  204  719  689  101  793 -460  959]
Valor mínimo da matriz:  -969
Valor mínimo por coluna:  [-878 -966 -969 -884 -881]
Valor mínimo por linha:  [  30 -878 -335 -863  -40 -289 -660 -239 -969 -966]
'''

'\nExercício 17\nCrie uma função que receba uma matriz como entrada e calcule:\n\n    a) Valor máximo da matriz;\n\n    b) Valor máximo por coluna;\n\n    c) Valor máximo por linha;\n\n    d) Valor mínimo da matriz;\n\n    e) Valor mínimo por coluna;\n\n    f) Valor mínimo por linha.\n\n\n\nExemplo de retorno para a matriz definida abaixo:\nInput:\n\nmatriz = np.random.randint(-1000,1000,50).reshape(10,5)\ninfo_matriz(matriz)\nOutput:\n\nValor máximo da matriz:  987\nValor máximo por coluna:  [959 987 597 748 719]\nValor máximo por linha:  [ 987  312  982  204  719  689  101  793 -460  959]\nValor mínimo da matriz:  -969\nValor mínimo por coluna:  [-878 -966 -969 -884 -881]\nValor mínimo por linha:  [  30 -878 -335 -863  -40 -289 -660 -239 -969 -966]\n'

In [55]:
def info_matrix(matrix):
  if isinstance(matrix,np.ndarray) and matrix.ndim == 2:
    print(f'Valor máximo da matriz: ', matrix.max())
    print(f'Valor máximo por coluna: ', matrix.max(axis = 0))
    print(f'Valor máximo por coluna: ', matrix.max(axis = 1))
    print(f'Valor mínimo da matriz: ', matrix.min())
    print(f'Valor mínimo por coluna: ', matrix.min(axis = 0))
    print(f'Valor mínimo por linha: ', matrix.min(axis =1))
  else:
    return None

if __name__=='__main__':
  matrix = np.random.randint(-1000,1000,50).reshape(10,5)
  info_matrix(matrix)

Valor máximo da matriz:  994
Valor máximo por coluna:  [938 901 842 994 894]
Valor máximo por coluna:  [652 994 613 113 894 938 484 931 620 759]
Valor mínimo da matriz:  -964
Valor mínimo por coluna:  [-936 -818 -821 -964 -797]
Valor mínimo por linha:  [-719 -461 -936 -821 -696 -736 -752 -797 -680 -964]


In [56]:
'''
Exercício 18
Com base no array definido abaixo obtenha sua média, mediana, variância e desvio padrão.
import numpy as np
arr = np.random.normal(40,0.5,size = (300))

Dica:

Média: np.mean();

Mediana: np.median();

Desvio padrão: np.std();

Variância: np.var().
'''

'\nExercício 18\nCom base no array definido abaixo obtenha sua média, mediana, variância e desvio padrão.\nimport numpy as np\narr = np.random.normal(40,0.5,size = (300))\n\nDica:\n\nMédia: np.mean();\n\nMediana: np.median();\n\nDesvio padrão: np.std();\n\nVariância: np.var().\n'

In [57]:
arr = np.random.normal(40,0.5,size = (300))

In [58]:
media = np.mean(arr)
print('Média: ', media)

Média:  40.030117690622305


In [59]:
mediana = np.median(arr)
print('Mediana: ', mediana)

Mediana:  40.0285726381289


In [60]:
desvio_padrao = np.std(arr)
print('Desvio Padrão: ', desvio_padrao)

Desvio Padrão:  0.4502688781069875


In [61]:
varianca = np.var(arr)
print('Variança: ', varianca)

Variança:  0.2027420625917252


In [62]:
'''
Exercício 19
Com base nos arrays definidos a seguir obtenha a matriz de covariância e a matriz de correlação.

import numpy as np
x = np.random.rand(100)
y = np.random.uniform(size=100)

Dica: use np.corrcoef() e np.cov().
'''

'\nExercício 19\nCom base nos arrays definidos a seguir obtenha a matriz de covariância e a matriz de correlação.\n\nimport numpy as np\nx = np.random.rand(100)\ny = np.random.uniform(size=100)\n\nDica: use np.corrcoef() e np.cov().\n'

In [63]:
x = np.random.rand(100)
y = np.random.uniform(size=100)

In [64]:
print(f'Matriz de correlação: {np.corrcoef(x,y)}')
print()
print(f'Matriz de covariância: {np.cov(x,y)}')


Matriz de correlação: [[ 1.        -0.1029524]
 [-0.1029524  1.       ]]

Matriz de covariância: [[ 0.07187773 -0.00703281]
 [-0.00703281  0.06492186]]


In [65]:
'''
Exercício 20
Obtenha o índice do valor máximo do array A.
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])


Dica: use np.argmax() ou array.argmax().
'''

'\nExercício 20\nObtenha o índice do valor máximo do array A.\nA = np.array([[11, 15, 33, 105],\n              [1, 140, 45, 90],\n              [67, 230, 78, 99]])\n\n\nDica: use np.argmax() ou array.argmax().\n'

In [66]:
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])


In [67]:
print(f'Valor máximo do array A: {A.max()}')
print(f'Indice do valor máximo do array A: {A.argmax()}')

Valor máximo do array A: 230
Indice do valor máximo do array A: 9


In [68]:
'''
Exercício 21
Obtenha o índice do valor mínimo do array B.
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])

Dica: use np.argmin() ou array.argmin().
'''

'\nExercício 21\nObtenha o índice do valor mínimo do array B.\nB = np.array([\n    [73, 22, 20, 62,  3],\n    [68, 84, 27, 59, 93],\n    [48, 52,  4, 55, 50],\n    [42, 23, 63, 67,  4],\n    [44, 30, 41, 31, 29]])\n\nDica: use np.argmin() ou array.argmin().\n'

In [69]:
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])


In [70]:
print(f'Valor mínimo do array B: {B.min()}')
print(f'Indíce do valor mínimo do array B: {B.argmin()}')

Valor mínimo do array B: 3
Indíce do valor mínimo do array B: 4


In [71]:
'''
Exercício 22
Escreva uma função que receba um array NumPy e mostre na tela um conjunto de  estatísticas descritivas deste objeto.

Resultado esperado:

Input

array = np.array([-57, 101, 270, 130, 144])
info_array(array)

Output:

Valor máximo: 270
Valor mínimo: -57
Média: 117.6
Mediana: 130.0
Variância: 10967.439999999999
Desvio padrão: 104.72554607162475
'''

'\nExercício 22\nEscreva uma função que receba um array NumPy e mostre na tela um conjunto de  estatísticas descritivas deste objeto.\n\nResultado esperado:\n\nInput\n\narray = np.array([-57, 101, 270, 130, 144])\ninfo_array(array)\n\nOutput:\n\nValor máximo: 270\nValor mínimo: -57\nMédia: 117.6\nMediana: 130.0\nVariância: 10967.439999999999\nDesvio padrão: 104.72554607162475\n'

In [72]:
def info_array(array):
  if isinstance(array, np.ndarray):
    print(f'Valor Máximo: ', array.max())
    print(f'Valor Mínimo: ', array.min())
    print(f'Média: ', array.mean())
    print(f'Médiana: ', np.median(array))
    print(f'Variança: ', array.var())
    print(f'Desvio Padrão: ', array.std())
  
  else:
    return None
  
if __name__=='__main__':
  array = np.array([-57, 101, 270, 130, 144])
  info_array(array) 

Valor Máximo:  270
Valor Mínimo:  -57
Média:  117.6
Médiana:  130.0
Variança:  10967.439999999999
Desvio Padrão:  104.72554607162475


In [73]:
'''
Exercício 23
Use a função np.unique() para obter um array com os elementos únicos do array abaixo. Para tanto, armazene o novo array em uma variável.
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])
'''

'\nExercício 23\nUse a função np.unique() para obter um array com os elementos únicos do array abaixo. Para tanto, armazene o novo array em uma variável.\nA = np.array([\n    [1, 3, 3, 4, 5],\n    [4, 7, 11, 3, 5],\n    [1, 11, 4, 4, 11]])\n'

In [74]:
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])

In [78]:
array_nulos = np.unique(A)
array_nulos

array([ 1,  3,  4,  5,  7, 11])

In [ ]:
'''
Exercício 24
Indexação de arrays 1-D
Considerando os arrays abaixo:
import numpy as np
array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
   
Obtenha:

a) o primeiro, o terceiro e o último elemento de cada array;

b) inverta o array;

c) pegue o número 20 em ambos os arrays e armazene a soma em uma variável.
'''

In [79]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
arrays = [array1, array2]

In [87]:
for index, array in enumerate(arrays, start = 1):
    print(f'Array {index}')
    print(f'Primeiro elemento: {array[0]}')
    print(f'Terceiro elemento: {array[2]}')
    print(f'Último elemento: {array[-1]}')
    print(f'Array invertido: {array[::-1]}')

soma = array1[1]  + array2[6]
print('Soma do número 20 de cada array:', soma)

Array 1
Primeiro elemento: 10
Terceiro elemento: 30
Último elemento: 40
Array invertido: [40 30 20 10]
Array 2
Primeiro elemento: 100
Terceiro elemento: 5
Último elemento: 170
Array invertido: [170 155 130  20 100  40   1   5  30 100]
Soma do número 20 de cada array: 40


In [ ]:
'''
Exercício 25
Indexação de arrays 2-D
Acesse os números 9 e 90 do array abaixo.
import numpy as np
ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])
'''

In [88]:
ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])

In [92]:
print(ar[0][3])
print(ar[1][3])

9
90


In [ ]:
'''
Exercício 26
Indexação de arrays 3-D
Acesse os números 5, 9, 3 e 21 do array abaixo.
import numpy as np
ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]
              ])
'''

In [93]:
ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]
              ])

In [101]:
print(ar[0][0][2]) #acessando número 5
print(ar[0][1][3]) #acessando número 9
print(ar[1][0][1]) #acessando número 3
print(ar[1][1][2]) #acessando número 21

5
9
3
21


In [ ]:
'''
Exercício 27
Slicing 1-D

Com base no array abaixo obtenha o slice do índice 2 até o índice 6.
import numpy as np
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Dica: Em Python, slicing significa que podemos selecionar elementos entre índices especificados. Sintaxe: [start:end:pass].

Se não especificarmos o start o valor default será 0. Se não definirmos o step, será considerado o valor 1.
'''

In [102]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [105]:
print(ar[2:7])

[3 4 5 6 7]
